repos:
  - repo: local
    hooks:
      - id: go-test
        name: Run Go Tests
        entry: bash -c "go test ./test/..."
        language: system
        pass_filenames: false
        always_run: true
