name: Build and Push Docker Image to Aliyun

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 1: Log in to Aliyun Docker registry
      - name: Log in to Aliyun Docker Registry
        run: |
          echo "${{ secrets.ALIYUN_DOCKER_PASSWORD }}" | docker login --username="${{ secrets.ALIYUN_DOCKER_USERNAME }}" --password-stdin registry.cn-hangzhou.aliyuncs.com

      # Step 2: Read the version from the .VERSION file
      - name: Read version from .VERSION file
        id: get_version
        run: |
          VERSION=$(cat .VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "The version from .VERSION file is: $VERSION"

      # Step 3: Convert repository name to lowercase and save to GITHUB_ENV
      - name: Convert repository name to lowercase
        run: |
          REPO_NAME=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
          echo "Repository name in lowercase: ${REPO_NAME}"

      # Step 4: Build the Docker image using the version from the .VERSION file
      - name: Build Docker Image
        run: |
          docker build -t ${REPO_NAME}:${VERSION} .

      # Step 5: Check if the Docker image already exists
      - name: Check if Docker Image Version Exists
        run: |
          IMAGE=registry.cn-hangzhou.aliyuncs.com/ledger_github/${REPO_NAME}:${VERSION}
          if docker manifest inspect $IMAGE > /dev/null 2>&1; then
            echo "Error: Docker image $IMAGE already exists. Exiting."
            exit 1
          fi
          echo "Docker image $IMAGE does not exist. Proceeding to push."

      # Step 6: Tag the image with the registry address and version
      - name: Tag Docker Image And Push
        if: success()
        run: |
          docker tag ${REPO_NAME}:${VERSION} registry.cn-hangzhou.aliyuncs.com/ledger_github/${REPO_NAME}:${VERSION}
          docker push registry.cn-hangzhou.aliyuncs.com/ledger_github/${REPO_NAME}:${VERSION}
